### ISSUE TITLE
Why inhibiting identity wires and not Events?

### ISSUE THREAD

**Issue by lattenwald** [Mokosha/netwire-input#1]
Discussion.

Doesn't it make more sense to handle keypresses and releases as events?

I wanted to reset one wire on space button, and I had to write stuff like

```
myWire = (keyNotPressed SDL_SCANCODE_SPACE . myRealWire)
         --> keyPressed SDL_SCANCODE_SPACE
         --> myWire
```

My intuition tells me it might be cleaner with Events (though I never messed with them enough to know for sure).

**Comment by Mokosha** [comment]
There's a wire that I use in my projects that may be a good addition to this library:

```
trigger :: GLFW.Key -> GameWire a a
trigger key = rSwitch mkId . (mkId &&& ((now . pure mkEmpty . keyPressed key) <|> never))
```

This wire behaves like the identity wire until you press the given key, and then inhibits forever. That way your resetting wire can be expressed succinctly as:

```
myWire = (myRealWire . trigger SDL_SCANCODE_SPACE) --> myWire
```

To answer your main question, the reason I stayed away from `Event` types is that I don't see a clean way to handle multiple button presses at a time. What would be the proper signature of such a function?

```
keyPressed :: (MonadKeyboard k m) => Wire s e m a (Event k) --?
keyEvent :: (MonadKeyboard k m) => Wire s e m a (Event (KeyEvent k)) --?
keysPressed :: (MonadKeyboard k m) => Wire s e m a [k] --?
keyEvent :: (MonadKeyboard k m) => k -> Wire s e m a (Event ()) --?
```

What happens when you're pressing two keys at the same time? What about when you press a key and release a different key in the same frame (time instant)? The only way to do that is to explicitly listen on a given key and receive events of that type. That being said, you can probably convert any inhibiting wire into an event-based wire:

```
import Control.Wire.Unsafe.Event
keyPressedEvent :: (MonadKeyboard k m) => k -> Wire s e m a (Event k)
keyPressedEvent key = pure (Event key) . keyPressed key <|> pure NoEvent
```

The other thing I didn't like about event-based wires is that I think that the existing combinators for manipulating events is much more oriented towards events that aren't triggered by the user. For example, the `asSoonAs` combinator would be great for handling behavior similar to `trigger` or `keyDebounced`, but it holds the same result forever after each event, making it hard to integrate into game-based applications (in my opinion, of course).

**Comment by lattenwald** [comment]
Ok, thanks for the answer, I have to think about it. Seems that I have to try dealing with events myself anyway.

**Comment by Mokosha** [comment]
Added events with #3 -- Closing.
